version: '3.8'

services:
  # PostgreSQL Database
  database:
    image: postgres:15-alpine
    container_name: medicare-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: medicare_user
      POSTGRES_PASSWORD: ${DB_PASSWORD:-medicare_secure_password_2024}
      POSTGRES_DB: medicare_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U medicare_user -d medicare_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - medicare-network

  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medicare-backend
    restart: unless-stopped
    ports:
      - "${PORT:-5000}:5000"
    environment:
      # Node environment
      NODE_ENV: production
      PORT: 5000
      
      # Database connection
      DATABASE_URL: postgresql://medicare_user:${DB_PASSWORD:-medicare_secure_password_2024}@database:5432/medicare_db
      
      # Add any other environment variables your app needs
      # JWT_SECRET: ${JWT_SECRET}
      # TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      # etc.
    depends_on:
      database:
        condition: service_healthy
    volumes:
      # Persist uploaded voice messages
      - ./uploads:/app/uploads
      # Firebase credentials (already copied in Dockerfile, but mount for updates)
      - ./medicare-244b3-firebase-adminsdk-fbsvc-21e2b2edf9.json:/app/medicare-244b3-firebase-adminsdk-fbsvc-21e2b2edf9.json:ro
    networks:
      - medicare-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Named volumes for data persistence
volumes:
  postgres_data:
    driver: local

# Custom network
networks:
  medicare-network:
    driver: bridge

